package com.liquiditylens.utils

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Paint
import android.graphics.Typeface
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

/**
 * Utility for capturing and sharing Canvas snapshots.
 * This is the viral growth engine - every shared image = free marketing.
 */
object SnapshotExporter {
    
    /**
     * Add watermark to bitmap with LiquidityLens branding.
     */
    fun addWatermark(bitmap: Bitmap): Bitmap {
        val result = bitmap.copy(Bitmap.Config.ARGB_8888, true)
        val canvas = Canvas(result)
        
        // Semi-transparent dark overlay at bottom
        val overlayPaint = Paint().apply {
            color = android.graphics.Color.argb(180, 13, 17, 23) // #0D1117 with alpha
            style = Paint.Style.FILL
        }
        canvas.drawRect(
            0f,
            result.height - 120f,
            result.width.toFloat(),
            result.height.toFloat(),
            overlayPaint
        )
        
        // Main branding text
        val textPaint = Paint().apply {
            color = android.graphics.Color.rgb(230, 237, 243) // #E6EDF3
            textSize = 48f
            typeface = Typeface.create(Typeface.MONOSPACE, Typeface.BOLD)
            isAntiAlias = true
        }
        canvas.drawText(
            "Generated by LiquidityLens",
            40f,
            result.height - 70f,
            textPaint
        )
        
        // Subtitle/URL
        val subtitlePaint = Paint().apply {
            color = android.graphics.Color.rgb(0, 230, 118) // #00E676 (neon green)
            textSize = 32f
            typeface = Typeface.create(Typeface.MONOSPACE, Typeface.NORMAL)
            isAntiAlias = true
        }
        canvas.drawText(
            "liquiditylens.io • Free Market DVR",
            40f,
            result.height - 30f,
            subtitlePaint
        )
        
        // Timestamp
        val timestamp = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.getDefault()).format(Date())
        val timestampPaint = Paint().apply {
            color = android.graphics.Color.rgb(136, 141, 147) // Grey
            textSize = 24f
            typeface = Typeface.create(Typeface.MONOSPACE, Typeface.NORMAL)
            isAntiAlias = true
        }
        canvas.drawText(
            timestamp,
            result.width - 380f,
            result.height - 30f,
            timestampPaint
        )
        
        return result
    }
    
    /**
     * Save bitmap to cache and return shareable URI.
     */
    fun saveToCacheAndGetUri(context: Context, bitmap: Bitmap): android.net.Uri? {
        return try {
            val cachePath = File(context.cacheDir, "images")
            cachePath.mkdirs()
            
            val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
            val file = File(cachePath, "liquiditylens_snapshot_$timestamp.png")
            
            FileOutputStream(file).use { stream ->
                bitmap.compress(Bitmap.CompressFormat.PNG, 100, stream)
            }
            
            FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }
    
    /**
     * Share snapshot via Android share sheet.
     */
    fun shareSnapshot(context: Context, bitmap: Bitmap, text: String = "Check out this market snapshot from LiquidityLens!") {
        val watermarkedBitmap = addWatermark(bitmap)
        val uri = saveToCacheAndGetUri(context, watermarkedBitmap)
        
        if (uri != null) {
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "image/png"
                putExtra(Intent.EXTRA_STREAM, uri)
                putExtra(Intent.EXTRA_TEXT, text)
                putExtra(Intent.EXTRA_SUBJECT, "LiquidityLens Market Snapshot")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            
            context.startActivity(Intent.createChooser(shareIntent, "Share Market Snapshot"))
        }
    }
}
